### ISSUE TITLE
NavigationContainer andnavigation context not found using expo router 

### ISSUE THREAD

**Issue by H4LV3D** [withmono/connect-react-native#47]
Error: Couldn't find a navigation context. Have you wrapped your app with 'NavigationContainer'? See https://reactnavigation.org/docs/getting-started for setup instructions.

I keep getting the error above wherever I place my MonoProvider. I am using expo SDK 50 with the new expo router. While reading the documentation. I understand that the Navigation Container is being completely handled by the expo router. What is the best possible solution?

`export default function RootLayout() {
  const [loaded, error] = useFonts({
    BricolageGrotesque: require("../assets/fonts/BricolageGrotesque/BricolageGrotesque_VariableFont_wght.ttf"),
    ...FontAwesome.font,
  });

  useEffect(() => {
    if (error) throw error;
  }, [error]);

  useEffect(() => {
    if (loaded) {
      SplashScreen.hideAsync();
    }
  }, [loaded]);

  if (!loaded) {
    return null;
  }

  const config = {
    publicKey: process.env.EXPO_PUBLIC_MONO_PUBLIC_KEY as string,
    scope: "auth",
    data: {
      customer: { id: "9876554432345678" },
    },
    onClose: () => alert("Widget closed"),
    onSuccess: (data: any) => {
      const code = data.getAuthCode();
      console.log("Access code", code);
    },
    onEvent: (eventName: any, data: any) => {
      // optional
      console.log(eventName);
      console.log(data);
    },
  };

  return (
    <MonoProvider {...config}>
      <NavigationContainer>
        <Stack
          initialRouteName="/(authenticated)/(tabs)"
          screenOptions={{
            headerShown: false,
          }}
        >
          <Stack.Screen name="index" options={{ title: "index" }} />
          <Stack.Screen name="onboarding" options={{ title: "onboarding" }} />
          <Stack.Screen name="signUp" options={{ title: "signup" }} />
          <Stack.Screen name="forgot" options={{ title: "forgot" }} />
          <Stack.Screen
            name="(authenticated)"
            options={{ headerShown: false }}
          />
          <Stack.Screen name="help" options={{ presentation: "modal" }} />
        </Stack>
      </NavigationContainer>
    </MonoProvider>
  );
}`

![Simulator Screen Shot - iPhone 14 Pro Max - 2024-05-05 at 17 34 14](https://github.com/withmono/connect-react-native/assets/64863887/58198675-6596-47ac-a83b-2ba4174e0d5d)

**Comment by naro-code-lab** [comment]
@H4LV3D I didn't get an error, I use expo 51.

**Comment by H4LV3D** [comment]
I had a meeting with the team and explained the error. An update was released yesterday that fixed the bug.

**Comment by H4LV3D** [comment]
This bug has been fixed in the current release @2.0.4

**Comment by naro-code-lab** [comment]
> I had a meeting with the team and explained the error. An update was released yesterday that fixed the bug. 
> 
> 

That's great! 👍
