### ISSUE TITLE
Non Responsive When Init Is Called

### ISSUE THREAD

**Issue by thecodecafe** [withmono/connect-react-native#6]
Hi, so I was integrating Mono and hit a snag, after following the docs and creating a button for initialising mono, I noticed that when I call init, nothing actually happens, I went into your provider's code and realised that you were using `createRef` to create a reference to the MonoConnect component, this I assumed is supposed to work but it seems createRef will always create a new reference, this possibly causes the current ref to be null when called even after being set, but as a solution changing `createRef` to `useRef` made it work in my case, please find the code, below.

```
...
function MonoProvider(props) {
    const ref = React.useRef<MonoConnectRefObj>()

   function init() {
       ref.current?.openWidget();
   }
   ...  
}
export default MonoProvider;
```
See [PR here](https://github.com/withmono/connect-react-native/pull/5#issue-540069253)

**Comment by umar-abdullahi** [comment]
Hello @thecodecafe , thank you for bringing this to our attention. For a solution to the problem you're having I'll suggest you lift up the provider to a level above in your component tree or extract the button with the `useMonoConnect` to a separate component. We would later provide an update to make this more intuitive. 

See example below for extracting component;
```js
function LinkAccount() {
  const { init } = useMonoConnect()

  return (
    <View style={{marginBottom: 10}}>
      <TouchableOpacity onPress={() => init()}>
        <Text style={{color: 'blue'}}>Link your bank account</Text>
      </TouchableOpacity>
    </View>
  )
}
```

Please let me know if you need any further assistance.

**Comment by thecodecafe** [comment]
Hi @umar-abdullahi, yes the provider actually envelopes my entire app, and the init function is called, but internally the reference to the mono connect component fails to initialize. so the ref remains null so `ref.current?.openWidget();` does not launch the widget, from my findings the ref variable needs to be initialised with `useRef` and not `createRef` you can check the PR I created to see the change made to the code.

**Comment by umar-abdullahi** [comment]
@thecodecafe I've seen your PR and would be reviewed and considered in the next update.

I can't replicate the issue you're having currently. Can you please share your code?

**Comment by thecodecafe** [comment]
Hi, @umar-abdullahi I just made another finding, so the PR I share will actually solve the problem, try doing this, do something that causes the MonoProvider to rerender, put it in a class component and update that class component before calling init, then you'll be able to reproduce, the thing is if you do that `createRef` will recreate the ref since the component is being updated reverting it back to null so when `init` is called the ref is not yet initialized, this prevents the widget from launching.

**Class Component**
```
import React from 'react';
import {
  ConfigsProviderProps,
  ConfigsProviderState,
  IMonoHandlers,
} from './interfaces';
import {MonoProvider} from '@mono.co/connect-react-native';
import ConfigsContext from './ConfigsContext';

export default class ConfigsProvider extends React.Component<
  ConfigsProviderProps,
  ConfigsProviderState
> {
  state: ConfigsProviderState = {
    isReady: false,
    monoKey: null,
    monoHandlers: null,
  };

  ...
  setMonoHandlers = (handlers?: IMonoHandlers) => {
    this.setState({monoHandlers: handlers || null});
  };

  handleMonoClose = () => {
    const {monoHandlers} = this.state;
    if (monoHandlers && monoHandlers.onClose) {
      monoHandlers.onClose();
    }
  };

  handleMonoSuccess = (data: any) => {
    const {monoHandlers} = this.state;
    if (monoHandlers && monoHandlers.onSuccess) {
      monoHandlers.onSuccess(data);
    }
  };

  render() {
    const {children} = this.props;
    const {isReady, monoKey} = this.state;
    return (
      <ConfigsContext.Provider
        value={{
          isReady: isReady,
          isMonoSet: !!monoKey,
          setMonoHandlers: this.setMonoHandlers,
        }}>
        <MonoProvider
          publicKey={monoKey}
          onClose={this.handleMonoClose}
          onSuccess={this.handleMonoSuccess}>
          {children}
        </MonoProvider>
      </ConfigsContext.Provider>
    );
  }
}
```

**Mono Button**
```
const MonoButton: React.FC<{
  disabled?: boolean;
  onInit?: (init: () => void) => void;
  children: string;
}> = function MonoButton({onInit, disabled, children}) {
  const {init} = useMonoConnect();
  if (!onWillInitialize) {
    return null;
  }
  return (
    <Button loading={disabled} onPress={() => onInit(init)}>
      {children}
    </Button>
  );
};
```

**Using The Mono Button**
```
<ConfigsContext.Consumer>
  {({setMonoHandlers}) => (
    <MonoButton onInit={async (initMono) => {
        setMonoHandlers({
            onSuccess: (result) => {
            // do something
            }
        });
        // wait for handlers to be set    
       setTimeout(initMono, 200);
    }}>
    </MonoButton>
  )}
</ConfigsContext.Consumer>
```
When I do this nothing happens.

Also, this is on the side, but it would be great if I can set the onSuccess, and onClose when calling init, it requires a lot handling success and close in a case where init is called at a deeper part of your application and if you want to handle the success and close callbacks from that level.

Thanks.

**Comment by umar-abdullahi** [comment]
@thecodecafe  using `MonoProvider` closer to where it's been used would solve both problems you're having, however to prevent the loss of value after re-renders we would remove the use of refs entirely. 

On the issue of passing `onClose` and `onSuccess` to the init function, that can be easily solved by using multiple `MonoProvider` , the `useMonoConnect` function return values based on the closest `MonoProvider` in the tree. 

**Providers can be nested to override values deeper within the tree.** see example below;

```js
function FirstWidgetLauncher() {
  const {init} = useMonoConnect();

  return (
    <Button onClick={init}>Authorise with Mono</Button>
  )
}
```

```js
function SecondWidgetLauncher() {
  const {init} = useMonoConnect();

  return (
    <Button onClick={init}>Authorise with Mono</Button>
  )
}

function AnotherSampleComponent() {
  const config = {
    key: "mono_public_key",
    onClose: () => console.log("close from second provider"),
    onSuccess: (data) => console.log("code from second provider", data.getAuthCode())  
  }

  return (
    <MonoProvider {...config}>
      <SecondWidgetLauncher />
   </MonoProvider>    
}

```
```js
function App() {
  const config = {
    key: "mono_public_key",
    onClose: () => console.log("close from first provider"),
    onSuccess: (data) => console.log("code from first provider", data.getAuthCode())  
  }

  return (
    <MonoProvider {...config}>
      <FirstWidgetLauncher />
      <AnotherSampleComponent />
   </MonoProvider>  
  )
}
```

**Comment by umar-abdullahi** [comment]
Please update to version `0.1.2`  and confirm if this issue is fixed thank you. [reference](https://github.com/withmono/connect-react-native/commit/95637a86037355c75542dbe083f5f561152f6d5b#diff-95ddb2d2a2716518eebfe99da6361d3e45057a7e4817f2cbcb8fa4805ef8d310)
